name: Cron
on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Get Token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v1
        with:
          application_id: ${{ secrets.BACKSTAGE_GOALIE_APPLICATION_ID }}
          application_private_key: ${{ secrets.BACKSTAGE_GOALIE_PRIVATE_KEY }}
          organization: backstage

      - uses: actions/checkout@v3

      - uses: backstage/actions/cron@v0.1.8
        with:
          github-token: ${{ steps.get_workflow_token.outputs.token }}
